version: '3.8'

services:
 notes:
  build:
   context: .
  ports:
   - 8000:8000
   - 9229:9229
  environment:
   - SERVER_PORT=8000
   #- CONNECTIONSTRING=mongodb://mongo:27017/node-todos
  volumes:
   - ./:/app
   - /app/node_modules
  networks:
    - node-todo_default
 mongo:
  image: mongo:4.2.8
  ports:
   - 27017:27017
  volumes:
   - mongodb:/data/db
   - mongodb_config:/data/configdb
  environment:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: example
  networks:
    - node-todo_default

volumes:
 mongodb:
 mongodb_config:

networks:
  node-todo_default:
    external: true